### ISSUE TITLE
Logo on Learn more and apply page seems big

### ISSUE THREAD

**Issue by jeremyloyd** [sparkbox/apprentices-page#45] opened 2014-10-16 18:48 UTC
I think we could use whatever size we arrive at on the homepage

![pasted_image_10_16_14__2_47_pm](https://cloud.githubusercontent.com/assets/1679752/4668402/fc70497c-5564-11e4-9aa6-326f6e6a515e.jpg)

**Comment by bryanbraun** [comment] 2016-03-18 20:16
Looks like this was fixed in #51 but the issue was never closed (I confirmed visually). Closing it now.

**Closed by bryanbraun** 2016-03-18 20:16 UTC
